/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    CateTree: typeof import('./components/CateTree/index.vue')['default']
    copy: typeof import('./components/Templates/Ttable copy.vue')['default']
    FileUpload: typeof import('./components/Templates/fileUpload.vue')['default']
    FileUploader: typeof import('./components/GiUpload/fileUploader.vue')['default']
    GiChart: typeof import('./components/GiChart/index.vue')['default']
    GiDot: typeof import('./components/GiDot/index.vue')['default']
    GiFlexibleBox: typeof import('./components/GiFlexibleBox/index.vue')['default']
    GiFooter: typeof import('./components/GiFooter/index.vue')['default']
    GiForm: typeof import('./components/GiForm/index.vue')['default']
    GiIconSelector: typeof import('./components/GiIconSelector/index.vue')['default']
    GiOption: typeof import('./components/GiOption/index.vue')['default']
    GiOptionItem: typeof import('./components/GiOptionItem/index.vue')['default']
    GiRadio: typeof import('./components/GiRadio/index.vue')['default']
    GiSelect: typeof import('./components/GiSelect/index.vue')['default']
    GiSvgIcon: typeof import('./components/GiSvgIcon/index.vue')['default']
    GiTable: typeof import('./components/GiTable/index.vue')['default']
    GiTag: typeof import('./components/GiTag/index.vue')['default']
    GiThemeBtn: typeof import('./components/GiThemeBtn/index.vue')['default']
    Icon403: typeof import('./components/icons/Icon403.vue')['default']
    Icon404: typeof import('./components/icons/Icon404.vue')['default']
    Icon500: typeof import('./components/icons/Icon500.vue')['default']
    IconBorders: typeof import('./components/icons/IconBorders.vue')['default']
    IconTableSize: typeof import('./components/icons/IconTableSize.vue')['default']
    IconTreeAdd: typeof import('./components/icons/IconTreeAdd.vue')['default']
    IconTreeReduce: typeof import('./components/icons/IconTreeReduce.vue')['default']
    ImageUploader: typeof import('./components/Templates/ImageUploader.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RightMenu: typeof import('./components/CateTree/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tdialog: typeof import('./components/Templates/Tdialog.vue')['default']
    Templates: typeof import('./components/Templates/index.vue')['default']
    Tform: typeof import('./components/Templates/Tform.vue')['default']
    Tradio: typeof import('./components/Templates/Tradio.vue')['default']
    TreeSwitcherIcon: typeof import('./components/CateTree/TreeSwitcherIcon.vue')['default']
    Tselect: typeof import('./components/Templates/Tselect.vue')['default']
    Ttable: typeof import('./components/Templates/Ttable.vue')['default']
    TuploadImg: typeof import('./components/Templates/TuploadImg.vue')['default']
    TuploadPdf: typeof import('./components/Templates/TuploadPdf.vue')['default']
    UplaodImg: typeof import('./components/GiUpload/uplaodImg.vue')['default']
    Verify: typeof import('./components/verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./components/verifition/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./components/verifition/Verify/VerifySlide.vue')['default']
    WangEdior: typeof import('./components/WangEdior/index.vue')['default']
  }
}
