/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    CateTree: typeof import('./components/CateTree/index.vue')['default']
    copy: typeof import('./components/GiUpload/fileUploader copy.vue')['default']
    FileUpload: typeof import('./components/GiUpload/fileUpload.vue')['default']
    FileUploader: typeof import('./components/GiUpload/fileUploader.vue')['default']
    GiChart: typeof import('./components/GiChart/index.vue')['default']
    GiDot: typeof import('./components/GiDot/index.vue')['default']
    GiFlexibleBox: typeof import('./components/GiFlexibleBox/index.vue')['default']
    GiFooter: typeof import('./components/GiFooter/index.vue')['default']
    GiForm: typeof import('./components/GiForm/index.vue')['default']
    GiIconSelector: typeof import('./components/GiIconSelector/index.vue')['default']
    GiOption: typeof import('./components/GiOption/index.vue')['default']
    GiOptionItem: typeof import('./components/GiOptionItem/index.vue')['default']
    GiRadio: typeof import('./components/GiRadio/index.vue')['default']
    GiSelect: typeof import('./components/GiSelect/index.vue')['default']
    GiSvgIcon: typeof import('./components/GiSvgIcon/index.vue')['default']
    GiTable: typeof import('./components/GiTable/index.vue')['default']
    GiTag: typeof import('./components/GiTag/index.vue')['default']
    GiThemeBtn: typeof import('./components/GiThemeBtn/index.vue')['default']
    ImageUploader: typeof import('./components/GiUpload/ImageUploader.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RightMenu: typeof import('./components/CateTree/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tform: typeof import('./components/GiForm/Tform.vue')['default']
    Tradio: typeof import('./components/GiRadio/Tradio.vue')['default']
    TreeSwitcherIcon: typeof import('./components/CateTree/TreeSwitcherIcon.vue')['default']
    Tselect: typeof import('./components/GiSelect/Tselect.vue')['default']
    UplaodImg: typeof import('./components/GiUpload/uplaodImg.vue')['default']
    Verify: typeof import('./components/verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./components/verifition/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./components/verifition/Verify/VerifySlide.vue')['default']
  }
}
